//
// Created by vince on 4/2/2023.
//

#ifndef POKER_ANALYSIS_RANKSENUM_H
#define POKER_ANALYSIS_RANKSENUM_H


enum ranksENUM{
    _ACE, _TWO, _THREE, _FOUR, _FIVE, _SIX, _SEVEN, _EIGHT, _NINE, _TEN, _JACK, _QUEEN, _KING
};


#endif //POKER_ANALYSIS_RANKSENUM_H
